package ru.klaus42.mysqldemo.components;

import org.springframework.beans.factory.annotation.Autowire;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import ru.klaus42.mysqldemo.entity.User;
import ru.klaus42.mysqldemo.repository.UserRepository;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

@Configurable(autowire = Autowire.BY_TYPE, dependencyCheck = true)
public class EmailValidator implements ConstraintValidator<EmailValid, String> {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Override
    public void initialize(EmailValid constraintAnnotation) {

    }

    @Override
    public boolean isValid(String contactField, ConstraintValidatorContext ctx) {

        User u = userRepository.findByEmail(contactField);

        return contactField != null && u == null;
    }
}
