package ru.klaus42.mysqldemo.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import ru.klaus42.mysqldemo.entity.Cash;
import ru.klaus42.mysqldemo.entity.User;
import ru.klaus42.mysqldemo.repository.UserRepository;

import java.util.List;
import java.util.Set;

@Controller
public class CashController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    @GetMapping("/user/cash")
    public String getUserProfile(Model model, Authentication authentication) {
        User user = userRepository.findByUsername(authentication.getName());

        Set<Cash> cashList = user.getCash();

        //User user = userRepository.findById(user_id).orElse(null);

        if (user == null) return "notfound";

        model.addAttribute("user", user);
        model.addAttribute("cashList",cashList);
        return "user/userprofile";
    }

}
